# Copyright (c) 2026 AIFoundry
# SPDX-License-Identifier: Apache-2.0
#
# Zephyr-U preempt-threads demo.

CONFIG_RISCV_RUN_IN_UMODE=y
CONFIG_MULTITHREADING=y
CONFIG_PRINTK=y
CONFIG_SYS_CLOCK_EXISTS=y
CONFIG_RISCV_UMODE_TIMER=y
CONFIG_TICKLESS_KERNEL=y
CONFIG_BOOT_BANNER=n

CONFIG_MAIN_STACK_SIZE=2048
CONFIG_IDLE_STACK_SIZE=512
CONFIG_ISR_STACK_SIZE=1024
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=1024

CONFIG_CONSOLE=n
CONFIG_SERIAL=n
