# Copyright (c) 2026 AIFoundry
# SPDX-License-Identifier: Apache-2.0
#
# Common settings. Board-specific configuration picks between U-mode
# ET-SoC1 and native M-mode Erbium.

CONFIG_MULTITHREADING=n
CONFIG_BOOT_BANNER=n
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_COMMON_LIBC_MALLOC=n
